name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: easy_saas_test
          MAX_ALLOWED_PACKET: 16M
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=15s --health-retries=3
    steps:
      - name: Verify MySQL connection from host
        run: |
          echo "${{ toJson(job) }}"
          sudo apt-get install -y mysql-client
          sudo ufw disable
          mysql --host 0.0.0.0 --port 3306 -uroot -psecret -e "SHOW DATABASES"
          docker logs "${{ job.services.mysql.id }}"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: easy_saas_test
          DB_PASSWORD: secret
        run: vendor/bin/phpunit
